// Asset manifest, loader and procedural placeholder fallbacks.
// If assets/<key>.png loads it is drawn; otherwise a canvas-primitive placeholder
// is drawn instead. The game is fully shippable with zero art files present.

import { STRINGS } from './strings.js';

export const MANIFEST = [
  'player_xwing',
  'player_xwing_force',
  'convoy_ship',
  'enemy_interceptor',
  'enemy_gunship',
  'enemy_lancer',
  'asteroid_s',
  'asteroid_m',
  'asteroid_l',
  'portrait_grogu',
  'portrait_grogu_tired',
  'portrait_grogu_spent',
  'portrait_mando',
  'portrait_luke',
  'bolt_red',
  'bolt_ion',
  'bg_stars_far',
  'bg_stars_mid',
  'bg_stars_near',
  'bg_nebula',
  'fx_explosion_big',
  'fx_explosion_small',
  'fx_muzzle_flash',
  'fx_force_wave',
];

// Per-sprite on-screen multiplier so the hand-drawn pixel art lands at the
// right size relative to each entity's hit radius. Call sites still pass their
// own scale; this is an additional base factor baked in here.
const BASE_SCALE = {
  player_xwing_force: 1.15,
  convoy_ship: 1.5,
  enemy_gunship: 1.4,
  enemy_lancer: 1.55,
  asteroid_s: 2,
  asteroid_m: 2,
  asteroid_l: 2,
  portrait_grogu: 1.4,
  portrait_grogu_tired: 1.4,
  portrait_grogu_spent: 1.4,
  portrait_mando: 1.4,
  portrait_luke: 1.4,
};

const images = new Map();

export function loadAssets() {
  return Promise.all(
    MANIFEST.map(
      (key) =>
        new Promise((resolve) => {
          const img = new Image();
          img.onload = () => {
            // 1x1 transparent sentinel files ship by default; real teammate art
            // is larger and replaces the procedural placeholder. Missing files
            // also degrade to the placeholder, never a crash.
            if (img.naturalWidth > 1 && img.naturalHeight > 1) {
              images.set(key, img);
            }
            resolve();
          };
          img.onerror = () => resolve();
          img.src = `./assets/${key}.png`;
        })
    )
  ).then(() => {
    // Asteroids have no teammate art yet: build crisp pixel-art rocks so they
    // match the hand-drawn sprites instead of the smooth vector placeholder.
    for (const [key, n, seed] of [
      ['asteroid_s', 18, 7],
      ['asteroid_m', 34, 23],
      ['asteroid_l', 56, 41],
    ]) {
      if (!images.has(key)) images.set(key, makeAsteroid(n, seed));
    }
  });
}

// Deterministic blocky asteroid. One canvas pixel == one art pixel; BASE_SCALE
// doubles it so every "pixel" is a clean 2x2 square on screen.
function makeAsteroid(n, seed) {
  const c = document.createElement('canvas');
  c.width = n;
  c.height = n;
  const g = c.getContext('2d');
  let s = seed >>> 0;
  const rnd = () => (s = (s * 1664525 + 1013904223) >>> 0) / 4294967296;
  const cx = (n - 1) / 2;
  const cy = (n - 1) / 2;
  const R = n * 0.46;
  const base = '#8a8577';
  const dark = '#5d594e';
  const edge = '#4f4b42';
  const lite = '#a49d8b';
  const lobes = 7;
  const amp = Array.from({ length: lobes }, () => 0.10 + rnd() * 0.20);
  for (let y = 0; y < n; y++) {
    for (let x = 0; x < n; x++) {
      const dx = (x - cx) / R;
      const dy = (y - cy) / R;
      const dist = Math.hypot(dx, dy);
      const ang = Math.atan2(dy, dx);
      let lim = 1;
      for (let k = 0; k < lobes; k++) lim += Math.cos(ang * (k + 1) + seed) * amp[k] * 0.32;
      if (dist <= lim) {
        let col = base;
        if (dist > lim - 0.18) col = edge;
        else if (-dx * 0.4 - dy * 0.4 > 0.15) col = lite;
        if (rnd() < 0.10) col = dark;
        g.fillStyle = col;
        g.fillRect(x, y, 1, 1);
      }
    }
  }
  const craters = 2 + Math.floor(rnd() * 2);
  for (let i = 0; i < craters; i++) {
    const a = rnd() * Math.PI * 2;
    const d = rnd() * 0.5;
    const px = cx + Math.cos(a) * d * R;
    const py = cy + Math.sin(a) * d * R;
    const cr = 1.5 + rnd() * 2.5;
    for (let y = Math.floor(py - cr - 1); y <= py + cr + 1; y++) {
      for (let x = Math.floor(px - cr - 1); x <= px + cr + 1; x++) {
        if (x < 0 || y < 0 || x >= n || y >= n) continue;
        const dd = Math.hypot(x - px, y - py);
        if (dd <= cr) {
          g.fillStyle = dark;
          g.fillRect(x, y, 1, 1);
        } else if (dd <= cr + 1) {
          g.fillStyle = edge;
          g.fillRect(x, y, 1, 1);
        }
      }
    }
  }
  return c;
}

// Raw Image/Canvas backing a loaded asset, for callers that need custom
// drawing (tiled backdrops, sprite-strip frames) instead of drawSprite's
// single centered blit.
export function getImage(key) {
  return images.get(key);
}

// Animation strips generated by project-sw are always square frames laid out
// left to right, frame size == strip height. No frame metadata needed.
export function stripFrameCount(key) {
  const img = images.get(key);
  if (!img) return 0;
  return Math.max(1, Math.round(img.width / img.height));
}

// Draws one frame of a strip, centered at (x, y). Returns false (drawing
// nothing) if the strip failed to load, so callers can skip gracefully.
export function drawStripFrame(key, ctx, x, y, frame, scale = 1, angle = 0) {
  const img = images.get(key);
  if (!img) return false;
  const size = img.height;
  const count = Math.max(1, Math.round(img.width / size));
  const f = ((Math.floor(frame) % count) + count) % count;
  ctx.save();
  ctx.translate(x, y);
  if (angle) ctx.rotate(angle);
  const d = size * scale;
  ctx.drawImage(img, f * size, 0, size, size, -d / 2, -d / 2, d, d);
  ctx.restore();
  return true;
}

export function drawSprite(key, ctx, x, y, angle = 0, scale = 1) {
  const img = images.get(key);
  const s = scale * (BASE_SCALE[key] || 1);
  ctx.save();
  ctx.translate(x, y);
  if (angle) ctx.rotate(angle);
  if (s !== 1) ctx.scale(s, s);
  if (img) {
    ctx.drawImage(img, -img.width / 2, -img.height / 2);
  } else {
    drawPlaceholder(key, ctx);
  }
  ctx.restore();
}

// ---------------------------------------------------------------------------
// Procedural placeholders. Original geometry only, drawn facing right.
// ---------------------------------------------------------------------------

function drawPlaceholder(key, ctx) {
  switch (key) {
    case 'player_xwing':
    case 'player_xwing_force':
      drawXwing(ctx);
      break;
    case 'convoy_ship':
      drawRazorCrest(ctx);
      break;
    case 'enemy_interceptor':
      drawInterceptor(ctx);
      break;
    case 'enemy_gunship':
      drawGunship(ctx);
      break;
    case 'enemy_lancer':
      drawLancer(ctx);
      break;
    case 'asteroid_s':
      drawRock(ctx, 18, '#8a8577', '#5d594e');
      break;
    case 'asteroid_m':
      drawRock(ctx, 34, '#8a8577', '#5d594e');
      break;
    case 'asteroid_l':
      drawRock(ctx, 56, '#7d786b', '#4f4b42');
      break;
    case 'portrait_grogu':
      drawGrogu(ctx, 'ok');
      break;
    case 'portrait_grogu_tired':
      drawGrogu(ctx, 'tired');
      break;
    case 'portrait_grogu_spent':
      drawGrogu(ctx, 'spent');
      break;
    case 'portrait_mando':
      drawMando(ctx);
      break;
    case 'portrait_luke':
      drawLuke(ctx);
      break;
    default:
      drawFallback(ctx);
  }
}

function drawXwing(ctx) {
  ctx.fillStyle = '#c9ccd2';
  ctx.strokeStyle = '#7c828d';
  ctx.lineWidth = 2;
  // fuselage
  ctx.beginPath();
  ctx.moveTo(44, 0);
  ctx.lineTo(6, -9);
  ctx.lineTo(-30, -7);
  ctx.lineTo(-30, 7);
  ctx.lineTo(6, 9);
  ctx.closePath();
  ctx.fill();
  ctx.stroke();
  // nose
  ctx.fillStyle = '#9aa0a8';
  ctx.beginPath();
  ctx.moveTo(56, 0);
  ctx.lineTo(40, -5);
  ctx.lineTo(40, 5);
  ctx.closePath();
  ctx.fill();
  // four wings in X
  ctx.fillStyle = '#b4432f';
  ctx.strokeStyle = '#7d2c1e';
  drawWing(ctx, -6, -10, 44, -34);
  drawWing(ctx, -6, 10, 44, 34);
  drawWing(ctx, -14, -8, 6, -40);
  drawWing(ctx, -14, 8, 6, 40);
  // cockpit
  ctx.fillStyle = '#3fd0e0';
  ctx.beginPath();
  ctx.ellipse(10, 0, 12, 6, 0, 0, Math.PI * 2);
  ctx.fill();
  // engines
  ctx.fillStyle = '#8d939c';
  ctx.fillRect(-30, -16, 12, 8);
  ctx.fillRect(-30, 8, 12, 8);
}

function drawWing(ctx, x1, y1, x2, y2) {
  ctx.beginPath();
  ctx.moveTo(x1, y1);
  ctx.lineTo(x1 + 10, y1 + (y1 < 0 ? -3 : 3));
  ctx.lineTo(x2, y2);
  ctx.lineTo(x2 - 8, y2);
  ctx.closePath();
  ctx.fill();
  ctx.stroke();
}

function drawRazorCrest(ctx) {
  ctx.fillStyle = '#9aa3ac';
  ctx.strokeStyle = '#5f676f';
  ctx.lineWidth = 3;
  ctx.beginPath();
  ctx.moveTo(-100, 30);
  ctx.lineTo(-96, -34);
  ctx.lineTo(30, -46);
  ctx.lineTo(84, -22);
  ctx.lineTo(90, -6);
  ctx.lineTo(70, 2);
  ctx.lineTo(24, 8);
  ctx.lineTo(30, 34);
  ctx.closePath();
  ctx.fill();
  ctx.stroke();
  // engine nacelles
  ctx.fillStyle = '#6c757e';
  ctx.fillRect(-104, -26, 20, 18);
  ctx.fillRect(-104, 10, 20, 18);
  // cockpit glass
  ctx.fillStyle = '#2b3b49';
  ctx.beginPath();
  ctx.moveTo(46, -18);
  ctx.lineTo(78, -14);
  ctx.lineTo(72, -2);
  ctx.lineTo(44, -6);
  ctx.closePath();
  ctx.fill();
  // weathering stripe
  ctx.fillStyle = '#c8b06a';
  ctx.fillRect(-70, 24, 70, 5);
}

function drawInterceptor(ctx) {
  ctx.fillStyle = '#5b626b';
  ctx.fillRect(-8, -6, 30, 12);
  ctx.fillStyle = '#3d434a';
  ctx.beginPath();
  ctx.ellipse(8, 0, 12, 9, 0, 0, Math.PI * 2);
  ctx.fill();
  ctx.fillStyle = '#7d8792';
  ctx.fillStyle = '#7d8792';
  drawHexPanel(ctx, -22, -26);
  drawHexPanel(ctx, -22, 26);
  ctx.fillStyle = '#99a3ad';
  ctx.beginPath();
  ctx.arc(6, 0, 4, 0, Math.PI * 2);
  ctx.fill();
}

function drawHexPanel(ctx, x, y) {
  ctx.beginPath();
  for (let i = 0; i < 6; i++) {
    const a = (Math.PI / 3) * i;
    const px = x + Math.cos(a) * 18;
    const py = y + Math.sin(a) * 18;
    if (i === 0) ctx.moveTo(px, py);
    else ctx.lineTo(px, py);
  }
  ctx.closePath();
  ctx.fill();
}

function drawGunship(ctx) {
  ctx.fillStyle = '#6f7680';
  ctx.strokeStyle = '#454b53';
  ctx.lineWidth = 2;
  ctx.beginPath();
  ctx.moveTo(-50, -30);
  ctx.lineTo(40, -38);
  ctx.lineTo(60, -16);
  ctx.lineTo(60, 16);
  ctx.lineTo(40, 38);
  ctx.lineTo(-50, 30);
  ctx.closePath();
  ctx.fill();
  ctx.stroke();
  ctx.fillStyle = '#4b5158';
  ctx.fillRect(-58, -14, 16, 28);
  ctx.fillStyle = '#2f3540';
  ctx.beginPath();
  ctx.ellipse(20, 0, 22, 15, 0, 0, Math.PI * 2);
  ctx.fill();
  ctx.fillStyle = '#8b949e';
  ctx.fillRect(40, -8, 26, 5);
  ctx.fillRect(40, 3, 26, 5);
}

function drawLancer(ctx) {
  ctx.fillStyle = '#4d5560';
  ctx.strokeStyle = '#2e343c';
  ctx.lineWidth = 3;
  ctx.beginPath();
  ctx.moveTo(-64, 0);
  ctx.lineTo(-30, -40);
  ctx.lineTo(46, -32);
  ctx.lineTo(64, 0);
  ctx.lineTo(46, 32);
  ctx.lineTo(-30, 40);
  ctx.closePath();
  ctx.fill();
  ctx.stroke();
  // long ion cannon
  ctx.fillStyle = '#7b6fb0';
  ctx.fillRect(52, -7, 58, 14);
  ctx.fillStyle = '#b7a8ff';
  ctx.beginPath();
  ctx.arc(112, 0, 7, 0, Math.PI * 2);
  ctx.fill();
  ctx.fillStyle = '#2f3540';
  ctx.beginPath();
  ctx.ellipse(0, 0, 22, 16, 0, 0, Math.PI * 2);
  ctx.fill();
}

function drawRock(ctx, r, fill, edge) {
  ctx.fillStyle = fill;
  ctx.strokeStyle = edge;
  ctx.lineWidth = 3;
  ctx.beginPath();
  const n = 9;
  for (let i = 0; i < n; i++) {
    const a = (Math.PI * 2 * i) / n;
    const wobble = 0.72 + Math.random() * 0.0; // stable silhouette handled below
    const rr = r * (0.82 + ((i * 37) % 20) / 100);
    const px = Math.cos(a) * rr;
    const py = Math.sin(a) * rr;
    if (i === 0) ctx.moveTo(px, py);
    else ctx.lineTo(px, py);
    void wobble;
  }
  ctx.closePath();
  ctx.fill();
  ctx.stroke();
  ctx.fillStyle = 'rgba(0,0,0,0.18)';
  ctx.beginPath();
  ctx.arc(-r * 0.2, r * 0.15, r * 0.35, 0, Math.PI * 2);
  ctx.fill();
}

function drawGrogu(ctx, state) {
  const droop = state === 'tired' ? 6 : state === 'spent' ? 14 : 0;
  ctx.save();
  ctx.translate(0, droop);
  // robe
  ctx.fillStyle = '#b7a06a';
  ctx.beginPath();
  ctx.moveTo(-30, 34);
  ctx.quadraticCurveTo(-38, -6, -22, -14);
  ctx.lineTo(22, -14);
  ctx.quadraticCurveTo(38, -6, 30, 34);
  ctx.closePath();
  ctx.fill();
  // head
  ctx.fillStyle = '#8fbf63';
  ctx.beginPath();
  ctx.ellipse(0, -22, 26, 22, 0, 0, Math.PI * 2);
  ctx.fill();
  // ears
  ctx.beginPath();
  ctx.moveTo(-24, -30);
  ctx.lineTo(-50, -46);
  ctx.lineTo(-24, -12);
  ctx.closePath();
  ctx.fill();
  ctx.beginPath();
  ctx.moveTo(24, -30);
  ctx.lineTo(50, -46);
  ctx.lineTo(24, -12);
  ctx.closePath();
  ctx.fill();
  // eyes
  ctx.fillStyle = '#1b1b1b';
  const eyeY = state === 'spent' ? -18 : -24;
  ctx.beginPath();
  ctx.arc(-9, eyeY, 4.5, 0, Math.PI * 2);
  ctx.arc(9, eyeY, 4.5, 0, Math.PI * 2);
  ctx.fill();
  if (state !== 'ok') {
    ctx.strokeStyle = '#3a3a3a';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(-15, eyeY - 8);
    ctx.lineTo(-4, eyeY - 4);
    ctx.moveTo(15, eyeY - 8);
    ctx.lineTo(4, eyeY - 4);
    ctx.stroke();
  }
  ctx.restore();
}

function drawMando(ctx) {
  ctx.fillStyle = '#8a949d';
  ctx.beginPath();
  ctx.ellipse(0, 0, 30, 36, 0, 0, Math.PI * 2);
  ctx.fill();
  ctx.fillStyle = '#20262d';
  ctx.beginPath();
  ctx.moveTo(-30, -2);
  ctx.lineTo(30, -2);
  ctx.lineTo(22, -22);
  ctx.lineTo(-22, -22);
  ctx.closePath();
  ctx.fill();
  ctx.fillStyle = '#3a4048';
  ctx.fillRect(-8, -34, 16, 22);
  ctx.fillStyle = '#c0392b';
  ctx.beginPath();
  ctx.arc(-13, -8, 2.4, 0, Math.PI * 2);
  ctx.arc(13, -8, 2.4, 0, Math.PI * 2);
  ctx.fill();
}

function drawLuke(ctx) {
  ctx.fillStyle = '#e0894a';
  ctx.beginPath();
  ctx.ellipse(0, -4, 30, 34, 0, 0, Math.PI * 2);
  ctx.fill();
  ctx.fillStyle = '#e7b48c';
  ctx.beginPath();
  ctx.ellipse(0, 6, 20, 20, 0, 0, Math.PI * 2);
  ctx.fill();
  ctx.fillStyle = '#2a2118';
  ctx.beginPath();
  ctx.ellipse(0, -10, 24, 9, 0, 0, Math.PI * 2);
  ctx.fill();
  ctx.fillStyle = '#3a6ea5';
  ctx.beginPath();
  ctx.arc(-7, 6, 3, 0, Math.PI * 2);
  ctx.arc(7, 6, 3, 0, Math.PI * 2);
  ctx.fill();
}

function drawFallback(ctx) {
  ctx.fillStyle = '#ff00ff';
  ctx.fillRect(-10, -10, 20, 20);
}

// Small helper used by ui for the character portraits if a key is missing.
export function characterName(key) {
  return STRINGS.characters[key] || key;
}